DROP DATABASE IF EXISTS DBJOGO;
CREATE DATABASE DBJOGO;

USE DBJOGO;

CREATE TABLE EQUIPAMENTO(
	CDEQUIPAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	TPEQUIPAMENTO CHAR(1),
	DESCRICAO VARCHAR(255),
	BONUS INT,
	FLEQUIPADO CHAR(1)
);

CREATE TABLE CLASSE(
	CDCLASSE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
	DESCRICAO VARCHAR(255),
	DANOMOD INT,
	VIDAMOD INT
);

CREATE TABLE PODER(
	CDPODER INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	DESCRICAO VARCHAR(255),
	FLEQUIPADO CHAR(1),
    CDCLASSE INT, FOREIGN KEY (CDCLASSE) REFERENCES CLASSE (CDCLASSE)
);

CREATE TABLE PERSONAGEM(
	CDPERSONAGEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    DANO INT,
    VIDA INT,
    CDCLASSE INT, FOREIGN KEY (CDCLASSE) REFERENCES CLASSE (CDCLASSE),
    CDEQUIPAMENTO INT, FOREIGN KEY (CDEQUIPAMENTO) REFERENCES EQUIPAMENTO (CDEQUIPAMENTO),
    CDPODER INT, FOREIGN KEY (CDPODER) REFERENCES PODER (CDPODER),
    EXPATUAL INT
);

CREATE TABLE REGIAO(
	CDREGIAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    DESCRICAO VARCHAR(255)
);

CREATE TABLE REGIAOPERSONAGEM (
	CDLOCALPERSONAGEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CDPERSONAGEM INT, FOREIGN KEY (CDPERSONAGEM) REFERENCES PERSONAGEM (CDPERSONAGEM),
    CDREGIAO INT, FOREIGN KEY (CDREGIAO) REFERENCES REGIAO (CDREGIAO),
    FLATUAL CHAR,
    FLVISITADO CHAR
);

INSERT INTO EQUIPAMENTO (NOME, TPEQUIPAMENTO, DESCRICAO, BONUS) 
	VALUES ('Espada', 'A' , "Espada longa de lamina dupla", 20);
INSERT INTO EQUIPAMENTO (NOME, TPEQUIPAMENTO, DESCRICAO, BONUS) 
	VALUES ('Maça', 'A' , "Maça estrela de aço", 25);
INSERT INTO EQUIPAMENTO (NOME, TPEQUIPAMENTO, DESCRICAO, BONUS) 
	VALUES ('Armadura Media', 'E' , "Feita de metal e couro", 30);
INSERT INTO EQUIPAMENTO (NOME, TPEQUIPAMENTO, DESCRICAO, BONUS) 
	VALUES ('Robe de conjurador', 'E' , "Um robe que parece encantado", 30);

INSERT INTO CLASSE (NOME, DESCRICAO, DANOMOD, VIDAMOD) 
	VALUES ("Paladino", "O Paladino é um guerreiro divino que usa suas habilidades sagradas para proteger seus aliados e eliminar seus inimigos.", 15, 50);
INSERT INTO CLASSE (NOME, DESCRICAO, DANOMOD, VIDAMOD) 
	VALUES ("Paladino", "O Mago é um mestre das artes arcanas que pode invocar poderosos feitiços para combater seus adversários e manipular a realidade.", 10, 30);

INSERT INTO PODER (NOME, DESCRICAO, CDCLASSE) 
	VALUES ("Golpe de Fé", "Imbuido sua arma com o poder de sua fé inabalavel: +30 de Dano no ataque", 1);
INSERT INTO PODER (NOME, DESCRICAO, CDCLASSE) 
	VALUES ("Cura Sagrada", "Suas mãos brilhão com um energia revitalizadora: +25 de vida", 1);
INSERT INTO PODER (NOME, DESCRICAO, CDCLASSE) 
	VALUES ("Raio de Fogo", "Dispara uma bola de fogo que viaja até seu alvo: 60 de dano", 2);
INSERT INTO PODER (NOME, DESCRICAO, CDCLASSE) 
	VALUES ("Toque Chocante", "Suas mãos se carregam com energia, descarregando ao toque: 40 de dano", 2);